#Firewall rules for SSH
- name: Disable conflicting services
  become: true
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  register: disable_service_result
  failed_when: (disable_service_result is failed)
               and ('Could not find the requested service' not in disable_service_result.msg)
  with_items:
    - iptables

- name : Install nftables
  become: true
  package:
    name: nftables
    state: present

- name: Remove ruleset
  become: true
  file: 
    path: /etc/nftables.conf  
    state: absent

- name: Copy rulset
  copy:
    dest: /etc/nftables.conf
    src: etc/nftables.conf
    owner: root
    group: root
    mode: 0644

- name: Start service nftables
  become: true
  service:
    name: nftables
    state: started

- name: Enable service nftables
  become: true
  service:
    name: nftables
    enabled: true



