
# Update and upgrade the system
- name: add repository deb
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  with_items:
    - regexp: "^deb .*"
      line: "deb http://httpredir.debian.org/debian buster main non-free contrib" 
    - regexp: "^deb-src.*"
      line: "deb-src http://httpredir.debian.org/debian buster main non-free contrib" 
   - regexp: ".*cdrom.*"
      line: "" 

# - name: Check repository deb
#   shell: grep "^deb " /etc/apt/sources.list | grep -v "^#" | grep -c "httpredir.debian.org" || true
#   register: test_rep-deb

# - name: Check repository deb-src
#   shell: grep "^deb-src " /etc/apt/sources.list | grep -v "^#" | grep -c "httpredir.debian.org" || true
#   register: test_rep-deb-src

# - name: add repository deb
#   lineinfile:
#     path: /etc/apt/sources.list
#     line: "{{ repo-deb }}'
#   when: test_rep-deb.stdout == "0"

#   - name: add repository deb
#   lineinfile:
#     path: /etc/apt/sources.list
#     line: "{{ repo-deb-src }}
#   when: test_rep-deb-src.stdout == "0"

- name: Update apt-get repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt: 
    upgrade: dist 
    force_apt_get: yes

- name: Upgrading Debian packages Debian
  apt:
    upgrade: dist


#- name: Check if a reboot is needed
#  register: reboot_required_file
#  stat: path=/var/run/reboot-required get_md5=no
#  notify: 
#  - reboot
#  when: reboot_required_file.stat.exists