
# Update and upgrade the system
- name: add repository deb
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Update apt-get repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt: 
    upgrade: dist 
    force_apt_get: yes

- name: Upgrading Debian packages Debian
  apt:
    upgrade: dist
